from rest_framework import serializers

class LocationSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    latitude = serializers.DecimalField(max_digits=12, decimal_places=6)
    longitude = serializers.DecimalField(max_digits=12, decimal_places=6)
    name = serializers.CharField(max_length=255, allow_null=True)
    address = serializers.CharField(allow_null=True)
    provinsi = serializers.CharField(max_length=255, allow_null=True)
    kabupaten_kota = serializers.CharField(max_length=255, allow_null=True)
    kecamatan = serializers.CharField(max_length=255,  allow_null=True)
    desa_kelurahan = serializers.CharField(max_length=255, allow_null=True)
    kode_pos = serializers.IntegerField(allow_null=True)
    is_dc = serializers.BooleanField(allow_null=True)
    created_at = serializers.DateTimeField(allow_null=True)
    updated_at = serializers.DateTimeField(allow_null=True)
    created_by = serializers.UUIDField(allow_null=True)
    updated_by = serializers.UUIDField(allow_null=True)
    is_deleted = serializers.BooleanField(allow_null=True)
    deleted_at = serializers.DateTimeField(allow_null=True)
    deleted_by = serializers.UUIDField(allow_null=True)
    open_hour = serializers.DateTimeField(allow_null=True)
    close_hour = serializers.DateTimeField(allow_null=True)
    dc_id = serializers.IntegerField(allow_null=True)
    company_id = serializers.IntegerField(allow_null=True)

class OrderSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    loc_dest = LocationSerializer()
    loc_ori = LocationSerializer()
    loc_dest_id = serializers.IntegerField()
    loc_ori_id = serializers.IntegerField()
    truck_id = serializers.IntegerField(allow_null=True)
    manifest_id =  serializers.IntegerField(allow_null=True)
    order_num = serializers.CharField(max_length=255,allow_null=True)
    description = serializers.CharField(allow_null=True)
    weight = serializers.DecimalField(max_digits=10, decimal_places=2, allow_null=True)
    volume = serializers.DecimalField(max_digits=10, decimal_places=2,allow_null=True)
    quantity = serializers.IntegerField(allow_null=True)
    status = serializers.CharField(max_length=255, allow_null=True)
    eta = serializers.DateTimeField(allow_null=True)
    etd = serializers.DateTimeField(allow_null=True)
    atd = serializers.DateTimeField(allow_null=True)
    ata = serializers.DateTimeField(allow_null=True)
    created_at = serializers.DateTimeField(allow_null=True)
    updated_at = serializers.DateTimeField(allow_null=True)
    created_by = serializers.UUIDField(allow_null=True)
    updated_by = serializers.UUIDField(allow_null=True)
    is_deleted = serializers.BooleanField(allow_null=True)
    deleted_at = serializers.DateTimeField(allow_null=True)
    deleted_by = serializers.UUIDField(allow_null=True)

   


