version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./restful_routing_project:/code
    ports:
      - "8000:8000"
    env_file:
      - ./restful_routing_project/.env
